# #Download postgres latest image
# docker pull postgres:latest

# #Create and run a container with postgres image
# docker run --name [container_name] -e POSTGRES_PASSWORD=[your_password] -d postgres

# #Connect to Postgres in docker container
# docker exec -it [container_name] psql -U [postgres_user]